{{- if .Values.ingress.enabled -}}
{{- $root := . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  {{- if eq .Release.Namespace .Values.namespaces.staging }}
  - host: {{ .Values.service.hostname }}-staging.{{.Values.basedomain}}
  {{ else if eq .Release.Namespace .Values.namespaces.production }}
  - host: {{ .Values.service.hostname }}.{{.Values.basedomain}}
  {{ else }}
  - host: {{ .Values.service.hostname }}-{{.Release.Namespace}}.{{ .Values.basedomain }}
  {{ end }}
    http:
      paths:
{{- range $port := .Values.ports }}
{{- if $port.public }}
      - path: {{ $port.url }}
        backend:
          serviceName: {{ $root.Values.service.key }}
          servicePort: {{ $port.externalPort }}
{{ end }}
{{- end }}
{{- end -}}
