apiVersion: v1
appVersion: 0.0.87
description: A Helm chart for Kubernetes
icon: https://raw.githubusercontent.com/jenkins-x/jenkins-x-platform/d273e09/images/go.png
name: atsea-shop-app
version: 0.0.87
